on:
  workflow_dispatch:

env:
  GH_AUTH_TOKEN: ${{ secrets.GH_AUTH_TOKEN }}
  JIRA_AUTH_TOKEN: ${{ secrets.JIRA_AUTH_TOKEN }}

jobs:
  Generate-JSON-File:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies and run application
        run: |
          echo "Running typescript application..."
          npm install
          npm install @types/node --save-dev
          npm install -g typescript
          npm install -g ts-node
          npm run start

      - name: Confirm application run
        run: |
          echo "Typescript application executed successfully!"
          echo "data.json file generated successfully!"

#      - name: Commit JSON file
#        run: |
#          git config --global user.email "mohammedafsar@propertyguru.com.sg"
#          git config --global user.name "afsarali-pg"
#          git remote set-url origin https://x-access-token:${GH_AUTH_TOKEN}@github.com/afsarali-pg/fintech-dashboard.git
#
#          git status
#          git add static/data/
#          git commit -m "updated data.json file with new data - $(date)"
#          git push origin main
#          echo "data.json file committed successfully!"

      - name: Auto commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "updated data.json file with new data - $(date)"
          file_pattern: "static/data/data.json"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_AUTH_TOKEN }}
          INPUT_COMMIT_USER_NAME: afsarali-pg
          INPUT_COMMIT_USER_EMAIL: mohammedafsar@propertyguru.com.sg

