on:
  workflow_dispatch:

env:
  GH_AUTH_TOKEN: ${{ secrets.GH_AUTH_TOKEN }}
  JIRA_AUTH_TOKEN: ${{ secrets.JIRA_AUTH_TOKEN }}

jobs:
  Generate-JSON-File:
    runs-on: ubuntu-latest
    permissions:
        contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies and run application
        run: |
          echo "Running typescript application..."
          npm install
          npm install @types/node --save-dev
          npm install -g typescript
          npm install -g ts-node
          npm run start

      - name: Confirm application run
        run: |
          echo "Typescript application executed successfully!"
          echo "data.json file generated successfully!"

      - name: Auto commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "updated data.json file with new data - $(date)"
          file_pattern: "static/data/data.json"

      - name: Trigger static.yml workflow
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { data } = await github.actions.createWorkflowDispatch({
              owner: 'afsarali-pg',
              repo: 'fintech-dashboard',
              workflow_file: '.github/workflows/static.yml',
              ref: 'main'
            })
            console.log(data)
